//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int address_id { get; set; }
        public string ward_name { get; set; }
        public string district_name { get; set; }
        public string province_name { get; set; }
        public string specific_address { get; set; }
        public int user_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
